version: '3'
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./src/db/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    tty: true
    ports:
      - 3306:3306
  web:
    build: .
    volumes:
      - ./src:/app
      - yarn-cache:/usr/local/share/.cache/yarn/v6
      - public-data:/app/public
      - tmp-data:/app/tmp
      - log-data:/app/log
    environment:
      RAILS_ENV: development
    depends_on:
      - db
    stdin_open: true
    tty: true
  nginx:
    build: 
      context: ./nginx
    ports:
      - 3000:3000
    depends_on:
      - web
    volumes:
      - public-data:/app/public
      - tmp-data:/app/tmp
volumes:
  yarn-cache:
  public-data:
  tmp-data:
  log-data:
