services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./src/db/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    tty: true
    ports:
      - 3306:3306
  web:
    build: .
    volumes:
      - ./src:/app
      - yarn-cache:/usr/local/share/.cache/yarn/v6
      # - public-data:/app/public
      # - tmp-data:/app/tmp
      # - log-data:/app/log
      - bundle_data:/usr/local/bundle:cached
    environment:
      RAILS_ENV: development
    depends_on:
      - db
    ports:
      - 3000:3000
    command: bundle exec rails server -b 0.0.0.0
    stdin_open: true
    tty: true
volumes:
  yarn-cache:
  # public-data:
  # tmp-data:
  # log-data:
  bundle_data:
