version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2-node-browsers
  heroku: circleci/heroku@1.2.3
  # node: circleci/node@2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7-node-browsers
    working_directory: ~/my_app03/src
    steps:
      - checkout:
          path: ~/my_app03
      - ruby/install-deps
  
  test:
    docker:
      - image: circleci/ruby:2.7
      - image: circleci/mysql:5.5
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: app_test
          MYSQL_USER: root
          NODE_ENV: test
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      APP_DATABASE_HOST: "127.0.0.1"
      RAILS_ENV: test
      NODE_ENV: test
    working_directory: ~/my_app03/src
    steps:
      - checkout:
          path: ~/my_app03
      - ruby/install-deps
      - run:
          name: webpacker
          command: bundle exec rails webpacker:compile
      - run:
          name: Database setup
          command: bundle exec rails db:migrate

      - run:
          name: test
          command: bundle exec rails test

  deploy:
    docker:
      - image: circleci/ruby:2.7
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - heroku/install
      - run:
          name: heroku login
          command: heroku container:login
      - run:
          name: push docker image
          command: heroku container:push web -a $HEROKU_APP_NAME
      - run:
          name: release docker image
          command: heroku container:release web -a $HEROKU_APP_NAME
      - run:
          name: database setup
          command: heroku run bundle exec rake db:migrate RAILS_ENV=production -a $HEROKU_APP_NAME

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - yarn_install      
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master