version: 2.1
orbs:
  ruby: circleci/ruby@1.1.4
  aws-ecr: circleci/aws-ecr@6.12.2
  aws-ecs: circleci/aws-ecs@1.3.0

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.3-node-browsers
    working_directory: ~/my_app03/src
    steps:
      - checkout:
          path: ~/my_app03
      - ruby/install-deps

  test:
    docker:
      - image: circleci/ruby:2.7-node-browsers
      - image: circleci/mysql:5.5
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: app_test
          MYSQL_USER: root
          NODE_ENV: test
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      APP_DATABASE_HOST: "127.0.0.1"
      RAILS_ENV: test
      NODE_ENV: test
    working_directory: ~/my_app03/src
    steps:
      - checkout:
          path: ~/my_app03
      - ruby/install-deps
      - run:
          name: Database setup
          command: bundle exec rails db:migrate
      - run: bundle install --path vendor/bundle
      - run:
          name: yarn Install
          command: yarn install
      - run: bundle exec bin/webpack
      - run:
          name: test
          command: bin/rspec

  deploy:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          account-url: AWS_ACCOUNT_URL
          repo: "myapp04"
          region: AWS_REGION
          tag: "${CIRCLE_SHA1}"

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build     
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
      - aws-ecs/deploy-service-update:
          requires:
            - deploy
          family: "myapp-web-fin"
          service-name: "myapp04"
          cluster-name: "myapp04-new"
          container-image-name-updates: "container=myapp-web,tag=${CIRCLE_SHA1}"
          filters:
            branches:
              only: master